builds:
- main: ./cmd/kubectl-prune/main.go
  ldflags: 
    - -s -w
    - -X github.com/micnncim/kubectl-prune/pkg/version.Version={{.Tag}}
    - -X github.com/micnncim/kubectl-prune/pkg/version.Revision={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows
