name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.15

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go test -v -race -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v1
        with:
          files: coverage.out
          verbose: true
